name: Auto commit changes

on:
  push:
    paths:
      - 'src/**'
  schedule:
    - cron: "36 7 * * *"
  workflow_dispatch: 

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 'automate'
        repository: 'krrishmahar/my_dsa'
        token: ${{ secrets.AUTOMATE_TOKEN }}

    - name: Configure, Commit and Push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "generated" || echo "Nothing to commit"
        git push

